#!/usr/bin/env bash
set -Eeuo pipefail
umask 0077

diagnostics="$(dirname -- "${BASH_SOURCE[0]}")/../lib/diagnostics.sh"
[[ -f "${diagnostics}" ]] || diagnostics=/usr/local/lib/solution-workspace/diagnostics.sh
if [[ ! -f "${diagnostics}" ]]; then
  printf '运维组件缺失：diagnostics.sh。请按部署手册的旧版更新器引导步骤安装完整运维组件。\n' >&2
  exit 1
fi
# shellcheck source=../lib/diagnostics.sh
source "${diagnostics}"

readonly DEFAULT_CONFIG_FILE="/etc/solution-workspace/deploy.conf"
CONFIG_FILE="${SOLUTION_WORKSPACE_CONFIG:-${DEFAULT_CONFIG_FILE}}"

usage() {
  cat <<'EOF'
Solution Workspace operations command.

Usage:
  sudo solution-workspace COMMAND [arguments]

Commands:
  status                         Show services, timer and health
  health                         Check backend readiness and frontend response
  doctor                         Read-only deployment and migration readiness checks
  start | stop | restart         Control the application target
  logs [backend|frontend|backup] [LINES]
                                 Show recent logs (default: both app services, 200)
  backup                         Create and verify an online SQLite backup
  verify-db DB_PATH              Verify SQLite integrity and backup manifest
  db-info                        Show active SQLite path and Alembic revision
  switch-db ABSOLUTE_DB_PATH     Switch to an existing or new SQLite database
  promote-db ABSOLUTE_DB_PATH    Clone the frozen active DB and promote the clone
  migrate                        Offline backup, then apply pending migrations
  create-admin LOGIN DISPLAY     Create a super administrator interactively
  update [REMOTE] [BRANCH]       Offline backup, fast-forward, build and deploy
                                 (defaults: origin main)
  update --offline BUNDLE [--branch BRANCH]
                                 校验同名 .sha256，自动识别单分支包并更新
                                 本地代码包；依赖缓存不足时仍需访问软件源
  help                           Show this help

Mutating commands use the root-owned deployment lock, so a backup,
database switch, migration or update cannot run concurrently.
EOF
}

COMMAND="${1:-help}"
if [[ "${COMMAND}" == "help" || "${COMMAND}" == "-h" || "${COMMAND}" == "--help" ]]; then
  usage
  exit 0
fi
shift || true

case "${COMMAND}" in
  status|health|doctor|start|stop|restart|backup|db-info|migrate)
    [[ "$#" -eq 0 ]] || fail "${COMMAND} 不接受额外参数；执行 solution-workspace help 查看用法。" E_ARGUMENT ;;
  logs) [[ "$#" -le 2 ]] || fail "用法：solution-workspace logs [backend|frontend|backup] [行数]" E_ARGUMENT ;;
  verify-db|switch-db|promote-db|create-admin|update) ;;
  *) fail "未知命令：${COMMAND}；执行 solution-workspace help 查看可用命令。" E_ARGUMENT ;;
esac
[[ "${EUID}" -eq 0 ]] || fail "权限不足，请使用 sudo solution-workspace ${COMMAND}。" E_PERMISSION
[[ -r "${CONFIG_FILE}" ]] || fail "部署配置不存在：${CONFIG_FILE}；新服务器请先运行 Ubuntu 安装脚本。" E_CONFIG
[[ ! -L "${CONFIG_FILE}" && "$(stat -c '%u' "${CONFIG_FILE}")" -eq 0 \
  && -z "$(find "${CONFIG_FILE}" -perm /022 -print)" ]] || {
  fail "部署配置必须由 root 持有、不可被其他账号写入且不能是符号链接：${CONFIG_FILE}" E_CONFIG
}
# The file is generated by the root-owned installer and is not user writable.
# shellcheck disable=SC1090
source "${CONFIG_FILE}"

required_values=(
  PROJECT_DIR APP_USER FRONTEND_USER APP_HOME NODE_BIN ENV_FILE DATA_DIR BACKUP_DIR
  FRONTEND_PORT BACKEND_PORT UV_PYTHON_INSTALL_DIR UV_CACHE_DIR LOCK_FILE
)
for required_name in "${required_values[@]}"; do
  [[ -n "${!required_name:-}" ]] || fail "部署配置 ${CONFIG_FILE} 缺少字段 ${required_name}，请检查安装是否完整。"
done

readonly PYTHON_BIN="${PROJECT_DIR}/.venv/bin/python"
readonly ALEMBIC_BIN="${PROJECT_DIR}/.venv/bin/alembic"
NODE_BIN_DIR="$(dirname -- "${NODE_BIN}")"
APP_GROUP="$(id -gn "${APP_USER}")" || fail "后端服务账号不存在：${APP_USER}；请修复部署账号。" E_CONFIG
FRONTEND_GROUP="$(id -gn "${FRONTEND_USER}")" || fail "前端服务账号不存在：${FRONTEND_USER}；请修复部署账号。" E_CONFIG
readonly NODE_BIN_DIR APP_GROUP FRONTEND_GROUP
readonly FRONTEND_HOME="/var/lib/solution-workspace-web-home"
readonly NPM_CACHE_DIR="/var/cache/solution-workspace/npm"
readonly SCHEDULED_BACKUP_DIR="${BACKUP_DIR}/scheduled"
export PATH="${NODE_BIN_DIR}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
RUNUSER_BIN="$(command -v runuser || true)"
readonly RUNUSER_BIN
[[ -x "${RUNUSER_BIN}" ]] || fail "缺少 runuser，请安装 util-linux。"
for required_command in git curl flock realpath sha256sum systemctl; do
  command -v "${required_command}" >/dev/null || fail "缺少命令 ${required_command}，请补齐系统依赖。" E_DEPENDENCY
done
[[ -f "${ENV_FILE}" && ! -L "${ENV_FILE}" && "$(stat -c '%u' "${ENV_FILE}")" -eq 0 \
  && -z "$(find "${ENV_FILE}" -perm /022 -print)" ]] || {
  fail "运行配置缺失或权限不安全：${ENV_FILE}；请恢复 root 持有的配置文件，勿重新生成加密密钥。" E_CONFIG
}
case "${COMMAND}" in
  update|backup|migrate|switch-db|promote-db) workspace_init_log "${COMMAND}" ;;
esac
MAINTENANCE_STARTED=false
PREVIOUS_APP_STATE=unknown
PREVIOUS_TIMER_STATE=unknown
DATA_MAY_HAVE_CHANGED=false
RECOVERY_SNAPSHOT=""

workspace_on_failure() {
  if [[ -n "${old_commit:-}" ]]; then
    printf '更新前提交：%s\n目标提交：%s\n前端恢复目录：%s\n前端切换状态：%s\n' \
      "${old_commit}" "${new_commit:-未知}" "${frontend_stage_dir:-未创建}" \
      "${frontend_runtime_swapped:-未开始}" | workspace_error_details
  fi
  if [[ "${SWITCH_ACTIVE:-false}" == true ]]; then
    rollback_switch "切库命令失败或被中断"
  elif [[ "${MAINTENANCE_STARTED}" == true ]]; then
    if [[ "${DATA_MAY_HAVE_CHANGED}" == false ]]; then
      if [[ "${PREVIOUS_APP_STATE}" == stopped ]]; then
        WORKSPACE_STATE="代码和数据库未更新；应用在操作前已停止，本次保持停止。"
        restore_previous_services || WORKSPACE_STATE="代码和数据库未更新，应用保持原来的停止状态；备份定时器恢复失败。"
      elif [[ "${PREVIOUS_APP_STATE}" != running ]]; then
        WORKSPACE_STATE="代码和数据库未更新；操作前服务并非全部正常运行，未自动启动，请执行 status 检查。"
      elif restore_previous_services; then
        WORKSPACE_STATE="代码和数据库未更新；原服务及备份定时器已恢复并通过健康检查。"
        if [[ "${PREVIOUS_TIMER_STATE}" != active ]]; then
          WORKSPACE_STATE="代码和数据库未更新；原应用已恢复并通过健康检查，备份定时器保持操作前的停止状态。"
        fi
      else
        WORKSPACE_STATE="代码和数据库未更新，但服务恢复未通过检查；请执行 status 和 logs 排查。"
      fi
    else
      stop_for_maintenance || true
      WORKSPACE_STATE="已尝试停止应用和备份定时器；代码或数据库可能已变更，请先执行 status 确认。"
      WORKSPACE_ADVICE="不要重复更新或迁移；按 docs/UBUNTU_DEPLOYMENT.md 的版本感知回滚步骤处理。"
    fi
  fi
  [[ -z "${RECOVERY_SNAPSHOT}" ]] || printf '回滚快照：%s\n' "${RECOVERY_SNAPSHOT}" | workspace_error_details
}

workspace_cleanup() {
  # Failed post-maintenance updates keep their runtime rollback directory.
  if [[ "${DATA_MAY_HAVE_CHANGED}" == false && -n "${frontend_stage_dir:-}" ]]; then
    cleanup_frontend_stage || true
  fi
  if [[ -n "${offline_stage:-}" && "${offline_stage}" == /var/lib/solution-workspace-releases/update.* \
    && -d "${offline_stage}" && ! -L "${offline_stage}" ]]; then
    rm -rf -- "${offline_stage}"
  fi
}

run_as_app() {
  "${RUNUSER_BIN}" -u "${APP_USER}" -- env \
    HOME="${APP_HOME}" \
    PATH="${PATH}" \
    bash -c 'umask 0077; exec "$@"' bash "$@"
}

run_as_frontend() {
  "${RUNUSER_BIN}" -u "${FRONTEND_USER}" -- env -i \
    HOME="${FRONTEND_HOME}" \
    LANG=C.UTF-8 \
    PATH="${PATH}" \
    npm_config_cache="${NPM_CACHE_DIR}" \
    npm_config_update_notifier=false \
    "$@"
}

run_app_env() {
  "${RUNUSER_BIN}" -u "${APP_USER}" -- env \
    HOME="${APP_HOME}" \
    PATH="${PATH}" \
    bash -c '
      set -Eeuo pipefail
      umask 0077
      set -a
      # shellcheck disable=SC1090
      source "$1"
      set +a
      cd "$2"
      shift 2
      exec "$@"
    ' bash "${ENV_FILE}" "${PROJECT_DIR}" "$@"
}

acquire_lock() {
  workspace_stage "等待运维锁" "有其他备份或部署任务运行时请等待其结束，不要删除锁文件。" E_LOCK
  exec 9>>"${LOCK_FILE}"
  flock --wait 300 9 || fail "等待 300 秒仍未取得运维锁：${LOCK_FILE}；另一项部署或备份可能仍在运行。" E_LOCK
}

health_check() {
  local attempts="${1:-1}"
  local delay_seconds="${2:-0}"
  local attempt
  for ((attempt = 1; attempt <= attempts; attempt += 1)); do
    if curl --fail --silent --show-error --connect-timeout 3 --max-time 10 \
      "http://127.0.0.1:${BACKEND_PORT}/api/v1/health/ready" >/dev/null \
      && curl --fail --silent --show-error --connect-timeout 3 --max-time 10 \
        "http://127.0.0.1:${FRONTEND_PORT}/" >/dev/null; then
      printf 'health: ok (backend :%s, frontend :%s)\n' \
        "${BACKEND_PORT}" "${FRONTEND_PORT}"
      return 0
    fi
    if ((attempt < attempts)); then
      sleep "${delay_seconds}"
    fi
  done
  printf '健康检查未通过：后端 http://127.0.0.1:%s/api/v1/health/ready；前端 http://127.0.0.1:%s/\n请执行 sudo solution-workspace status 和 sudo solution-workspace logs。\n' "${BACKEND_PORT}" "${FRONTEND_PORT}" >&2
  return 1
}

create_backup() {
  local output_dir="$1"
  [[ -d "${output_dir}" && ! -L "${output_dir}" ]] || {
    fail "备份输出目录不存在或为符号链接：${output_dir}"
  }
  run_app_env "${PYTHON_BIN}" -m app.backup --output-dir "${output_dir}"
}

verify_database() {
  local database_path="$1"
  [[ -f "${database_path}" ]] || fail "数据库文件不存在：${database_path}"
  run_as_app "${PYTHON_BIN}" -c '
import hashlib
import json
import sqlite3
import sys
from pathlib import Path

path = Path(sys.argv[1]).resolve()
with sqlite3.connect(f"{path.as_uri()}?mode=ro", uri=True) as db:
    result = db.execute("PRAGMA integrity_check").fetchone()
    tables = {
        row[0]
        for row in db.execute("SELECT name FROM sqlite_master WHERE type = '\''table'\''")
    }
    revision_row = (
        db.execute("SELECT version_num FROM alembic_version LIMIT 1").fetchone()
        if "alembic_version" in tables
        else None
    )
if not result or result[0] != "ok":
    raise SystemExit(f"integrity_check failed: {result}")

manifest_path = path.with_name(path.name + ".manifest.json")
manifest_state = "not present (integrity only)"
if manifest_path.is_file():
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    hasher = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            hasher.update(chunk)
    if manifest.get("databaseFile") != path.name:
        raise SystemExit("manifest databaseFile does not match")
    if manifest.get("sha256") != hasher.hexdigest():
        raise SystemExit("manifest SHA-256 does not match")
    if manifest.get("sizeBytes") != path.stat().st_size:
        raise SystemExit("manifest size does not match")
    manifest_state = "verified"
revision = revision_row[0] if revision_row else "none (empty or pre-migration DB)"
print(
    f"database integrity: ok; manifest: {manifest_state}; "
    f"schema revision: {revision}; file: {path}"
)
' "${database_path}"
}

secure_database_permissions() {
  local database_path="$1"
  "${PYTHON_BIN}" - "${DATA_DIR}" "${database_path}" \
    "$(id -u "${APP_USER}")" "$(id -g "${APP_USER}")" <<'PY'
import os
import stat
import sys

data_root, database_path, uid_text, gid_text = sys.argv[1:]
parent, filename = os.path.split(database_path)
if parent != data_root or not filename or "/" in filename:
    raise SystemExit("database must be a direct child of the data directory")

directory_flags = os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW
file_flags = os.O_RDONLY | os.O_NOFOLLOW
directory_fd = os.open(data_root, directory_flags)
try:
    database_fd = os.open(filename, file_flags, dir_fd=directory_fd)
    try:
        if not stat.S_ISREG(os.fstat(database_fd).st_mode):
            raise SystemExit("database target is not a regular file")
        os.fchown(database_fd, int(uid_text), int(gid_text))
        os.fchmod(database_fd, 0o600)
    finally:
        os.close(database_fd)
finally:
    os.close(directory_fd)
PY
}

rewrite_database_url() {
  local new_url="$1"
  local temporary_env
  temporary_env="$(mktemp "${ENV_FILE%/*}/app.env.XXXXXX")"
  awk -v replacement="MVP_DATABASE_URL=${new_url}" '
    BEGIN { replaced = 0 }
    /^MVP_DATABASE_URL=/ {
      print replacement
      replaced = 1
      next
    }
    { print }
    END {
      if (!replaced) {
        print replacement
      }
    }
  ' "${ENV_FILE}" >"${temporary_env}"
  install -m 0640 -o root -g "${APP_GROUP}" "${temporary_env}" "${ENV_FILE}.next"
  mv -f -- "${ENV_FILE}.next" "${ENV_FILE}"
  rm -f -- "${temporary_env}"
}

active_database_url() {
  sed -n 's/^MVP_DATABASE_URL=//p' "${ENV_FILE}" | tail -n1
}

active_database_path() {
  local url
  url="$(active_database_url)"
  [[ "${url}" == sqlite:////* ]] || fail "当前数据库配置不是文件型 SQLite 绝对路径，请检查 app.env。"
  realpath --canonicalize-missing -- "${url#sqlite:///}"
}

new_operation_dir() {
  local category="$1"
  local timestamp category_dir output_dir
  case "${category}" in
    switches|migrations|updates) ;;
    *) fail "invalid operation backup category: ${category}" ;;
  esac
  timestamp="$(date -u +%Y%m%dT%H%M%S%NZ)"
  category_dir="${BACKUP_DIR}/${category}"
  output_dir="${category_dir}/${timestamp}"
  [[ ! -L "${category_dir}" ]] || return 1
  install -d -m 0750 -o root -g "${APP_GROUP}" "${category_dir}" || return 1
  [[ ! -L "${category_dir}" ]] || return 1
  install -d -m 0770 -o root -g "${APP_GROUP}" "${output_dir}" || return 1
  printf '%s\n' "${output_dir}"
}

restart_unchanged_and_fail() {
  local message="$1"
  fail "${message}" E_DATABASE
}

backup_file_in() {
  local backup_dir="$1"
  local matches
  shopt -s nullglob
  matches=("${backup_dir}"/mvp-*.db)
  shopt -u nullglob
  [[ "${#matches[@]}" -eq 1 ]] || fail "回滚目录 ${backup_dir} 中没有唯一的数据库快照，不能继续操作。"
  printf '%s\n' "${matches[0]}"
}

stop_for_maintenance() {
  local stopped=true unit state previous_backend previous_frontend
  if [[ "${MAINTENANCE_STARTED}" == false ]]; then
    previous_backend="$(systemctl show --property=ActiveState --value solution-workspace-backend.service)" || return 1
    previous_frontend="$(systemctl show --property=ActiveState --value solution-workspace-frontend.service)" || return 1
    PREVIOUS_TIMER_STATE="$(systemctl show --property=ActiveState --value solution-workspace-backup.timer)" || return 1
    if [[ "${previous_backend}" == active && "${previous_frontend}" == active ]]; then
      PREVIOUS_APP_STATE=running
    elif [[ "${previous_backend}" =~ ^(inactive|failed)$ && "${previous_frontend}" =~ ^(inactive|failed)$ ]]; then
      PREVIOUS_APP_STATE=stopped
    fi
  fi
  MAINTENANCE_STARTED=true
  WORKSPACE_STATE="已进入维护阶段，服务可能部分停止。"
  systemctl stop solution-workspace-backup.timer || stopped=false
  systemctl stop solution-workspace-backup.service || stopped=false
  systemctl stop solution-workspace.target || stopped=false
  systemctl stop solution-workspace-backend.service solution-workspace-frontend.service || stopped=false
  for unit in solution-workspace-backup.timer solution-workspace-backup.service \
    solution-workspace-backend.service solution-workspace-frontend.service; do
    state="$(systemctl show --property=ActiveState --value "${unit}")" || stopped=false
    [[ "${state}" == inactive || "${state}" == failed ]] || stopped=false
  done
  [[ "${stopped}" == true ]] || return 1
  WORKSPACE_STATE="应用和备份定时器已停止。"
}

restore_previous_services() {
  case "${PREVIOUS_APP_STATE}" in
    running)
      systemctl start solution-workspace.target || return 1
      health_check 3 1 || return 1
      ;;
    stopped) ;;
    *) return 1 ;;
  esac
  if [[ "${PREVIOUS_TIMER_STATE}" == active ]]; then
    systemctl start solution-workspace-backup.timer || return 1
    systemctl is-active --quiet solution-workspace-backup.timer || return 1
  fi
}

clone_sqlite_database() {
  local source_path="$1"
  local target_path="$2"
  run_as_app "${PYTHON_BIN}" -c '
import sqlite3
import sys
from contextlib import closing
from pathlib import Path

source_path, target_path = sys.argv[1:3]
with (
    closing(sqlite3.connect(f"{Path(source_path).as_uri()}?mode=ro", uri=True)) as source,
    closing(sqlite3.connect(target_path)) as target,
):
    source.backup(target)
    target.commit()
' "${source_path}" "${target_path}"
}

checkpoint_database() {
  local database_path="$1"
  run_as_app "${PYTHON_BIN}" -c '
import sqlite3
import sys

with sqlite3.connect(sys.argv[1]) as db:
    checkpoint = db.execute("PRAGMA wal_checkpoint(TRUNCATE)").fetchone()
    if checkpoint and checkpoint[0] != 0:
        raise SystemExit("数据库仍有事务占用，无法完成 WAL 检查点；未移动数据库文件")
    result = db.execute("PRAGMA integrity_check").fetchone()
    if not result or result[0] != "ok":
        raise SystemExit(f"integrity_check failed: {result}")
' "${database_path}"
}

move_database_bundle() {
  local source_path="$1"
  local target_path="$2"
  local suffix
  [[ -f "${source_path}" ]] || return 1
  mv -- "${source_path}" "${target_path}" || return 1
  for suffix in -wal -shm; do
    if [[ -e "${source_path}${suffix}" ]]; then
      mv -- "${source_path}${suffix}" "${target_path}${suffix}" || return 1
    fi
  done
}

SWITCH_ACTIVE="false"
SWITCH_ENV_SNAPSHOT=""
SWITCH_TARGET=""
SWITCH_PRESERVED_TARGET=""
SWITCH_CANDIDATE=""
SWITCH_TIMESTAMP=""
SWITCH_SWAPPED="false"
SWITCH_FILES_UNCERTAIN=false

rollback_switch() {
  local reason="$1"
  local restored=true
  trap - ERR
  set +e
  if ! stop_for_maintenance; then
    WORKSPACE_STATE="切库恢复中止：无法确认服务全部停止；未继续移动数据库或配置。"
    WORKSPACE_ADVICE="先执行 status 和 logs；确认服务停止后，按回滚快照及 app.env.before 恢复。"
    SWITCH_ACTIVE=false
    return 1
  fi
  if [[ "${SWITCH_FILES_UNCERTAIN}" == true ]]; then
    WORKSPACE_STATE="数据库文件移动未完整结束，应用已停止；未尝试覆盖文件或自动恢复。"
    WORKSPACE_ADVICE="保留候选库、目标库及 ${SWITCH_ENV_SNAPSHOT}，核对完整文件组后按迁机/恢复手册处理。"
    SWITCH_ACTIVE=false
    return 1
  fi
  if [[ "${SWITCH_SWAPPED}" == "true" && -f "${SWITCH_TARGET}" ]]; then
    move_database_bundle \
      "${SWITCH_TARGET}" \
      "${SWITCH_TARGET}.failed-${SWITCH_TIMESTAMP}" || restored=false
  fi
  if [[ "${restored}" == true && -n "${SWITCH_PRESERVED_TARGET}" && -f "${SWITCH_PRESERVED_TARGET}" ]]; then
    move_database_bundle "${SWITCH_PRESERVED_TARGET}" "${SWITCH_TARGET}" || restored=false
  fi
  if [[ "${restored}" == true && -n "${SWITCH_CANDIDATE}" && -f "${SWITCH_CANDIDATE}" ]]; then
    move_database_bundle "${SWITCH_CANDIDATE}" "${SWITCH_CANDIDATE}.failed" || restored=false
  fi
  if [[ -f "${SWITCH_ENV_SNAPSHOT}" ]]; then
    if ! install -m 0640 -o root -g "${APP_GROUP}" "${SWITCH_ENV_SNAPSHOT}" "${ENV_FILE}.restore" \
      || ! mv -f -- "${ENV_FILE}.restore" "${ENV_FILE}"; then
      restored=false
    fi
  else
    restored=false
  fi
  if [[ "${restored}" == true ]] && restore_previous_services; then
    if [[ "${PREVIOUS_APP_STATE}" == running ]]; then
      WORKSPACE_STATE="切库失败，原数据库及配置已恢复，原服务通过健康检查。"
    else
      WORKSPACE_STATE="切库失败，原数据库及配置已恢复；应用保持操作前的停止状态。"
    fi
    MAINTENANCE_STARTED=false
  else
    stop_for_maintenance || true
    WORKSPACE_STATE="切库失败，恢复未完成；已尝试停服，请执行 status 确认，勿重复切库。"
    WORKSPACE_ADVICE="检查日志与 ${SWITCH_ENV_SNAPSHOT}，按部署手册恢复；不要删除失败候选库。"
  fi
  SWITCH_ACTIVE="false"
  printf '切库恢复处理：%s\n' "${reason}" >&2
}

switch_error_trap() {
  local status="$1"
  WORKSPACE_ERROR="切库过程中命令失败或操作被中断。"
  exit "${status}"
}

switch_database() {
  local mode="$1"
  local requested_path="$2"
  local target_path data_root current_path rollback_dir rollback_db source_path new_url

  [[ "${requested_path}" == /* ]] || fail "数据库路径必须是以 / 开头的绝对路径。"
  [[ ! -L "${requested_path}" ]] || fail "目标数据库不能是符号链接。" E_DATABASE
  [[ "${requested_path}" != *[[:space:]]* ]] || fail "数据库路径不能包含空格或换行。"
  [[ "${requested_path}" != *"'"* ]] || fail "数据库路径不能包含单引号。"
  target_path="$(realpath --canonicalize-missing -- "${requested_path}")"
  data_root="$(realpath -- "${DATA_DIR}")"
  [[ "$(dirname -- "${target_path}")" == "${data_root}" ]] || {
    fail "数据库必须直接放在 ${data_root} 根层，不能位于嵌套目录。"
  }
  [[ "${target_path}" == *.db ]] || fail "数据库文件名必须以 .db 结尾。"
  acquire_lock
  workspace_stage "校验数据库切换条件" "目标数据库须位于数据目录根层；检查路径、权限和备份校验清单。" E_DATABASE
  current_path="$(active_database_path)"
  [[ "${target_path}" != "${current_path}" ]] || fail "目标数据库已经在使用，无需切换。"

  workspace_stage "停服并备份当前数据库" "确认服务已停止并检查备份目录空间；失败时会尝试恢复未变更的服务。" E_BACKUP
  stop_for_maintenance
  [[ ! -L "${requested_path}" ]] || restart_unchanged_and_fail "维护期间目标数据库变成了符号链接。"
  target_path="$(realpath --canonicalize-missing -- "${requested_path}")"
  data_root="$(realpath -- "${DATA_DIR}")"
  [[ "$(dirname -- "${target_path}")" == "${data_root}" \
    && "${target_path}" == *.db ]] || {
    restart_unchanged_and_fail "进入维护后数据库路径发生变化，已取消切换。"
  }
  [[ "${target_path}" != "${current_path}" ]] || {
    restart_unchanged_and_fail "目标路径指向了当前数据库，已取消切换。"
  }
  if [[ "${mode}" == "switch" && -f "${target_path}" ]]; then
    [[ ! -L "${target_path}" ]] || {
      restart_unchanged_and_fail "目标数据库是符号链接，已取消切换。"
    }
    if ! secure_database_permissions "${target_path}" \
      || ! verify_database "${target_path}"; then
      restart_unchanged_and_fail "目标数据库校验失败；请检查完整性、配套清单和文件权限。"
    fi
  elif [[ "${mode}" == "promote" && -e "${target_path}" ]]; then
    restart_unchanged_and_fail "promote-db 目标文件已存在；请使用新的文件名，避免覆盖已有数据库。"
  fi

  if ! rollback_dir="$(new_operation_dir switches)"; then
    fail "无法创建切库回滚目录，请检查备份目录权限和空间。"
  fi
  if ! create_backup "${rollback_dir}"; then
    fail "停服备份失败，尚未切换数据库。"
  fi
  if ! rollback_db="$(backup_file_in "${rollback_dir}")"; then
    fail "找不到切库回滚快照，尚未切换数据库。"
  fi
  RECOVERY_SNAPSHOT="${rollback_db}"
  SWITCH_ENV_SNAPSHOT="${rollback_dir}/app.env.before"
  if ! install -m 0640 -o root -g "${APP_GROUP}" \
    "${ENV_FILE}" "${SWITCH_ENV_SNAPSHOT}"; then
    fail "无法备份运行配置，尚未切换数据库。"
  fi
  SWITCH_TIMESTAMP="$(date -u +%Y%m%dT%H%M%S%NZ)"
  SWITCH_TARGET="${target_path}"
  SWITCH_CANDIDATE="${DATA_DIR}/.switch-candidate-${SWITCH_TIMESTAMP}.db"
  SWITCH_PRESERVED_TARGET=""
  SWITCH_SWAPPED="false"
  SWITCH_ACTIVE="true"
  trap 'switch_error_trap 130' INT
  trap 'switch_error_trap 143' TERM

  if [[ "${mode}" == "promote" ]]; then
    source_path="${rollback_db}"
  elif [[ -f "${target_path}" ]]; then
    checkpoint_database "${target_path}"
    source_path="${target_path}"
  else
    source_path=""
  fi
  if [[ -n "${source_path}" ]]; then
    clone_sqlite_database "${source_path}" "${SWITCH_CANDIDATE}"
  fi

  new_url="sqlite:///${SWITCH_CANDIDATE}"
  DATA_MAY_HAVE_CHANGED=true
  workspace_stage "迁移候选数据库" "候选库迁移失败会尝试恢复原配置；请保留回滚快照。" E_MIGRATION
  rewrite_database_url "${new_url}"
  if ! workspace_run run_app_env "${ALEMBIC_BIN}" upgrade head; then
    fail "候选数据库迁移失败。"
  fi
  checkpoint_database "${SWITCH_CANDIDATE}"

  if [[ -f "${target_path}" ]]; then
    SWITCH_PRESERVED_TARGET="${target_path}.pre-switch-${SWITCH_TIMESTAMP}"
    SWITCH_FILES_UNCERTAIN=true
    move_database_bundle "${target_path}" "${SWITCH_PRESERVED_TARGET}"
    SWITCH_FILES_UNCERTAIN=false
  fi
  SWITCH_FILES_UNCERTAIN=true
  move_database_bundle "${SWITCH_CANDIDATE}" "${target_path}"
  SWITCH_SWAPPED="true"
  SWITCH_FILES_UNCERTAIN=false
  secure_database_permissions "${target_path}"
  rewrite_database_url "sqlite:///${target_path}"

  if ! systemctl start solution-workspace.target || ! health_check 12 2; then
    fail "切换后服务启动或健康检查失败。"
  fi
  systemctl start solution-workspace-backup.timer
  systemctl is-active --quiet solution-workspace-backup.timer
  SWITCH_ACTIVE="false"
  MAINTENANCE_STARTED=false
  trap - ERR INT TERM
  printf 'database switch completed: %s\n' "${target_path}"
  printf 'offline rollback snapshot: %s\n' "${rollback_db}"
  if [[ -n "${SWITCH_PRESERVED_TARGET}" ]]; then
    printf 'pre-migration target preserved: %s\n' "${SWITCH_PRESERVED_TARGET}"
  fi
}

prepare_offline_bundle() {
  local input="$1" checksum="${1}.sha256" checksum_line expected actual refs ref _commit
  [[ -f "${input}" && ! -L "${input}" && -r "${input}" ]] || {
    fail "找不到可读的普通 bundle 文件：${input}；请确认上传路径，不能使用目录或符号链接。" E_BUNDLE_FILE
  }
  [[ -f "${checksum}" && ! -L "${checksum}" && -r "${checksum}" ]] || {
    fail "缺少配套校验文件：${checksum}；请上传与 bundle 同一批生成的 .sha256 文件。" E_CHECKSUM_FILE
  }
  local releases=/var/lib/solution-workspace-releases
  [[ ! -L "${releases}" ]] || fail "发布暂存目录不能是符号链接：${releases}" E_BUNDLE_FILE
  install -d -m 0700 -o root -g root "${releases}"
  workspace_require_space "${releases}" "$(( $(stat -c '%s' -- "${input}") + 10485760 ))"
  offline_stage="$(mktemp -d "${releases}/update.XXXXXXXX")"
  install -m 0600 -o root -g root -- "${input}" "${offline_stage}/release.bundle"
  install -m 0600 -o root -g root -- "${checksum}" "${offline_stage}/release.sha256"
  # Parse exactly one digest, never execute the file or pass its paths to sha256sum.
  checksum_line="$(cat "${offline_stage}/release.sha256")"
  checksum_line="${checksum_line%$'\r'}"
  [[ "${checksum_line}" =~ ^([[:xdigit:]]{64})[[:blank:]]+\*?(.+)$ \
    && "${BASH_REMATCH[2]}" == "$(basename -- "${input}")" ]] || {
    fail "校验文件格式或文件名不匹配；请重新上传同一批生成的 bundle 和 .sha256，不要混用不同版本。" E_CHECKSUM_FORMAT
  }
  expected="${BASH_REMATCH[1],,}"
  actual="$(sha256sum "${offline_stage}/release.bundle")"
  actual="${actual%% *}"
  [[ "${actual}" == "${expected}" ]] || {
    fail "安装包 SHA-256 不一致，可能上传不完整；请重新上传两个配套文件。" E_CHECKSUM_MISMATCH
  }
  workspace_run git -C "${PROJECT_DIR}" bundle verify "${offline_stage}/release.bundle" || {
    fail "bundle 验证失败：包可能损坏，或服务器缺少增量包所需的历史提交。缺少基线时请使用 -FullHistory 重新打包。" E_BUNDLE_VERIFY
  }
  refs="$(git bundle list-heads "${offline_stage}/release.bundle")" || fail "无法读取 bundle 分支。" E_BUNDLE_VERIFY
  local -a heads=()
  while read -r _commit ref; do
    [[ "${ref}" == refs/heads/* ]] && heads+=("${ref#refs/heads/}")
  done <<<"${refs}"
  if [[ -z "${branch}" ]]; then
    [[ "${#heads[@]}" -eq 1 ]] || fail "包内有 ${#heads[@]} 个分支，无法自动选择；请使用 --branch 分支名指定目标。" E_BUNDLE_BRANCH
    branch="${heads[0]}"
  fi
  expected_commit="$(awk -v ref="refs/heads/${branch}" '$2 == ref {print $1}' <<<"${refs}")"
  [[ "${expected_commit}" =~ ^[[:xdigit:]]{40,64}$ ]] || fail "bundle 中不存在分支 ${branch}；请核对打包分支或 --branch 参数。" E_BUNDLE_BRANCH
  remote="${offline_stage}/release.bundle"
  printf '更新包校验通过；目标分支：%s；目标提交：%s\n' "${branch}" "${expected_commit}"
}

read_database_revision() {
  local database_path
  database_path="$(active_database_path)" || return 1
  # Alembic current loads the application engine, which can create a missing
  # database and change its journal mode. Diagnostics must only read the file.
  run_as_app "${PYTHON_BIN}" -c '
import sqlite3
import sys
from contextlib import closing
from pathlib import Path

path = Path(sys.argv[1])
try:
    with closing(sqlite3.connect(f"{path.as_uri()}?mode=ro", uri=True)) as db:
        revisions = [row[0] for row in db.execute("SELECT version_num FROM alembic_version")]
    if not revisions:
        raise ValueError("数据库没有迁移版本记录")
except (OSError, sqlite3.Error, ValueError) as error:
    print(f"数据库版本读取失败：{path}；{error}。请核对原数据库路径、权限和迁移记录，未创建或迁移数据库。", file=sys.stderr)
    raise SystemExit(1) from None
print(f"数据位置：{path}")
print("数据库版本：" + ", ".join(revisions))
' "${database_path}"
}

doctor() {
  local failures=0 project_status
  workspace_stage "只读检查部署状态" "按下方问题逐项检查；数据库不存在时请恢复正确路径或备份，勿重新生成密钥。" E_DOCTOR
  printf '部署检查（只读，不输出配置密钥）\n'
  git -C "${PROJECT_DIR}" log -1 --format='代码版本：%h %s' || failures=$((failures + 1))
  if ! project_status="$(git --no-optional-locks -C "${PROJECT_DIR}" status --porcelain)"; then
    printf '需处理：无法读取代码目录的 Git 状态，请检查路径和权限。\n'; failures=$((failures + 1))
  elif [[ -n "${project_status}" ]]; then
    printf '需处理：代码目录存在本地修改，更新前必须妥善保存。\n'; failures=$((failures + 1))
  fi
  read_database_revision || failures=$((failures + 1))
  health_check || failures=$((failures + 1))
  systemctl is-active --quiet solution-workspace-backup.timer || {
    printf '需处理：自动备份定时器未运行。\n'; failures=$((failures + 1))
  }
  systemctl is-enabled --quiet solution-workspace-backup.timer || {
    printf '需处理：自动备份定时器未设为开机启用。\n'; failures=$((failures + 1))
  }
  df -h -- "${PROJECT_DIR}" "${DATA_DIR}" "${BACKUP_DIR}" || failures=$((failures + 1))
  printf '迁机需单独转移：经过校验的数据库及 manifest、app.env（含原加密密钥）、对应版本代码；操作步骤见部署手册。\n'
  ((failures == 0)) || fail "发现 ${failures} 项待处理问题，请按上方提示逐项检查。" E_DOCTOR
}

case "${COMMAND}" in
  doctor)
    doctor
    ;;
  status)
    systemctl --no-pager --full status \
      solution-workspace.target \
      solution-workspace-backend.service \
      solution-workspace-frontend.service \
      solution-workspace-backup.timer || true
    printf '\n'
    health_check || true
    ;;
  health)
    workspace_stage "检查服务响应" "执行 status 和 logs，核对服务启动日志、端口和代理配置。" E_HEALTH
    health_check 12 2
    ;;
  start|stop|restart)
    acquire_lock
    workspace_stage "执行服务操作：${COMMAND}" "执行 sudo solution-workspace status 和 logs，确认实际状态后再处理。" E_SERVICE
    WORKSPACE_STATE="已请求 ${COMMAND}；服务可能处于部分启动或停止状态，请以 status 和健康检查为准。"
    systemctl "${COMMAND}" solution-workspace.target
    if [[ "${COMMAND}" == stop ]]; then
      systemctl stop solution-workspace-backend.service solution-workspace-frontend.service
    else
      workspace_stage "检查启停后的服务响应" "检查失败服务的日志；不要把进程已启动当作应用已就绪。" E_HEALTH
      health_check 12 2
    fi
    ;;
  logs)
    component="${1:-all}"
    lines="${2:-200}"
    [[ "${lines}" =~ ^[0-9]+$ ]] || fail "日志行数必须是非负整数。"
    case "${component}" in
      backend) units=(-u solution-workspace-backend.service) ;;
      frontend) units=(-u solution-workspace-frontend.service) ;;
      backup) units=(-u solution-workspace-backup.service) ;;
      all) units=(-u solution-workspace-backend.service -u solution-workspace-frontend.service) ;;
      *) fail "日志类型必须为 backend、frontend、backup 或 all。" ;;
    esac
    journalctl --no-pager --full "${units[@]}" -n "${lines}"
    ;;
  backup)
    [[ "$#" -eq 0 ]] || fail "usage: solution-workspace backup"
    acquire_lock
    workspace_stage "创建并验证数据库备份" "检查数据文件及备份目录权限、磁盘空间；失败的备份不能用于迁机。" E_BACKUP
    workspace_run create_backup "${SCHEDULED_BACKUP_DIR}"
    ;;
  verify-db)
    [[ "$#" -eq 1 ]] || fail "usage: solution-workspace verify-db DB_PATH"
    workspace_stage "校验数据库与备份清单" "核对数据库和同名 manifest 是否配套，查看具体完整性或哈希错误；不要使用未通过校验的备份。" E_DATABASE_VERIFY
    verify_database "$1"
    ;;
  db-info)
    workspace_stage "读取数据库位置和版本" "检查运行配置、Python 环境及数据库文件权限；本操作不执行迁移。" E_DATABASE
    read_database_revision
    ;;
  switch-db)
    [[ "$#" -eq 1 ]] || fail "usage: solution-workspace switch-db ABSOLUTE_DB_PATH"
    switch_database switch "$1"
    ;;
  promote-db)
    [[ "$#" -eq 1 ]] || fail "usage: solution-workspace promote-db ABSOLUTE_DB_PATH"
    switch_database promote "$1"
    ;;
  migrate)
    acquire_lock
    workspace_stage "停服并创建迁移前备份" "检查停止服务和备份错误，确认原版本状态后再重试。" E_BACKUP
    stop_for_maintenance
    if ! migration_dir="$(new_operation_dir migrations)"; then
      fail "无法创建数据库迁移回滚目录。"
    fi
    if ! create_backup "${migration_dir}"; then
      fail "数据库迁移前备份失败，尚未执行迁移。"
    fi
    if ! migration_backup="$(backup_file_in "${migration_dir}")"; then
      fail "找不到数据库迁移回滚快照，尚未执行迁移。"
    fi
    RECOVERY_SNAPSHOT="${migration_backup}"
    DATA_MAY_HAVE_CHANGED=true
    workspace_stage "执行数据库迁移" "迁移失败时不要连续重试；保留快照和日志并按部署手册恢复。" E_MIGRATION
    if ! workspace_run run_app_env "${ALEMBIC_BIN}" upgrade head; then
      printf 'migration failed; services remain stopped\n' >&2
      printf 'offline rollback snapshot: %s\n' "${migration_backup}" >&2
      fail "迁移或启动失败；请先检查日志和回滚快照，不要直接重启或重复迁移。"
    fi
    workspace_stage "检查迁移后的服务响应" "保留迁移前快照，检查服务日志；健康检查失败时保持维护状态。" E_HEALTH
    if ! systemctl start solution-workspace.target || ! health_check 12 2; then
      systemctl stop solution-workspace.target || true
      systemctl stop solution-workspace-backend.service solution-workspace-frontend.service || true
      systemctl stop solution-workspace-backup.timer solution-workspace-backup.service || true
      printf 'migration startup/health failed; services remain stopped\n' >&2
      printf 'offline rollback snapshot: %s\n' "${migration_backup}" >&2
      fail "迁移或启动失败；请先检查日志和回滚快照，不要直接重启或重复迁移。"
    fi
    systemctl start solution-workspace-backup.timer
    systemctl is-active --quiet solution-workspace-backup.timer
    MAINTENANCE_STARTED=false
    printf '数据库迁移及服务健康检查完成；回滚快照：%s\n' "${migration_backup}"
    ;;
  create-admin)
    [[ "$#" -eq 2 ]] || fail 'usage: solution-workspace create-admin LOGIN "DISPLAY NAME"'
    acquire_lock
    workspace_stage "创建管理员账号" "按交互提示输入资料；若连接中断，重试前先检查账号是否已经创建。" E_ACCOUNT
    WORKSPACE_STATE="管理员创建命令可能已写入数据库；服务未因本次操作启停。"
    run_app_env "${PYTHON_BIN}" -m app.cli create-user "$1" "$2" --role super_admin
    ;;
  update)
    remote=origin
    branch=main
    offline_input=""
    expected_commit=""
    offline_stage=""
    if [[ "${1:-}" == --offline ]]; then
      [[ "$#" -ge 2 && -n "$2" && "$2" != --* ]] || fail "用法：update --offline /路径/更新包.bundle [--branch 分支名]" E_ARGUMENT
      offline_input="$2"
      branch=""
      shift 2
      if [[ "$#" -gt 0 ]]; then
        [[ "$#" -eq 2 && "$1" == --branch && -n "$2" ]] || fail "离线更新只接受 --branch 分支名；请检查额外参数。" E_ARGUMENT
        branch="$2"
      fi
    else
      [[ "$#" -le 2 && "${1:-}" != -* ]] || fail "用法：update [远程或本地 bundle] [分支]，或 update --offline 文件.bundle。" E_ARGUMENT
      remote="${1:-origin}"
      branch="${2:-main}"
    fi
    if [[ -n "${branch}" ]]; then
      git check-ref-format --branch "${branch}" >/dev/null 2>&1 || fail "无效分支名：${branch}" E_ARGUMENT
      [[ "${branch}" != -* && "${branch}" != *@* ]] || fail "请提供明确的分支名称。" E_ARGUMENT
    fi
    frontend_stage_dir=""
    frontend_runtime_swapped="false"
    cleanup_frontend_stage() {
      local candidate="${frontend_stage_dir:-}"
      local canonical_parent canonical_candidate expected_prefix
      [[ -n "${candidate}" ]] || return 0
      [[ -d "${candidate}" && ! -L "${candidate}" ]] || return 1
      canonical_parent="$(realpath -- "$(dirname -- "${PROJECT_DIR}")")" || return 1
      canonical_candidate="$(realpath -- "${candidate}")" || return 1
      expected_prefix="${canonical_parent}/$(basename -- "${PROJECT_DIR}").frontend-update."
      [[ "${canonical_candidate}" == "${expected_prefix}"* ]] || {
        printf 'refusing to remove unexpected frontend staging path: %s\n' \
          "${canonical_candidate}" >&2
        return 1
      }
      rm -rf -- "${canonical_candidate}" || return 1
      frontend_stage_dir=""
    }
    validate_staged_frontend() {
      local staged_frontend="${frontend_stage_dir}/frontend"
      local candidate_path expected_path
      [[ -d "${staged_frontend}" && ! -L "${staged_frontend}" ]] || return 1
      expected_path="$(realpath -- "${frontend_stage_dir}")/frontend"
      [[ "$(realpath -- "${staged_frontend}")" == "${expected_path}" ]] || return 1
      for candidate_path in node_modules dist; do
        [[ -d "${staged_frontend}/${candidate_path}" ]] || return 1
        [[ ! -L "${staged_frontend}/${candidate_path}" ]] || return 1
        [[ "$(realpath -- "${staged_frontend}/${candidate_path}")" == \
          "${expected_path}/${candidate_path}" ]] || return 1
      done
      [[ -f "${staged_frontend}/node_modules/vinext/dist/cli.js" ]] || return 1
      [[ ! -L "${staged_frontend}/node_modules/vinext/dist/cli.js" ]] || return 1
      [[ "$(realpath -- "${staged_frontend}/node_modules/vinext/dist/cli.js")" == \
        "${expected_path}/node_modules/vinext/dist/cli.js" ]] || return 1
      [[ -f "${staged_frontend}/dist/server/index.js" ]] || return 1
      [[ ! -L "${staged_frontend}/dist/server/index.js" ]] || return 1
      [[ "$(realpath -- "${staged_frontend}/dist/server/index.js")" == \
        "${expected_path}/dist/server/index.js" ]] || return 1
    }
    set_frontend_runtime_state() {
      local state="$1"
      case "${state}" in
        false|in_progress|true) ;;
        *) return 1 ;;
      esac
      sed -i "s/^FRONTEND_RUNTIME_SWAPPED=.*$/FRONTEND_RUNTIME_SWAPPED=${state}/" \
        "${update_dir}/update.env" || return 1
      sync -f "${update_dir}/update.env" || return 1
      sync -f "${update_dir}" || return 1
      frontend_runtime_swapped="${state}"
    }
    swap_frontend_runtime() {
      local staged_frontend="${frontend_stage_dir}/frontend"
      local live_frontend="${PROJECT_DIR}/frontend"
      local previous_frontend="${frontend_stage_dir}/previous"
      local had_node_modules=0
      local had_dist=0

      validate_staged_frontend || return 1
      install -d -m 0700 "${previous_frontend}"
      if [[ -e "${live_frontend}/node_modules" ]]; then
        mv -- "${live_frontend}/node_modules" "${previous_frontend}/node_modules"
        had_node_modules=1
      fi
      if [[ -e "${live_frontend}/dist" ]]; then
        if ! mv -- "${live_frontend}/dist" "${previous_frontend}/dist"; then
          if ((had_node_modules)); then
            mv -- "${previous_frontend}/node_modules" "${live_frontend}/node_modules"
          fi
          return 1
        fi
        had_dist=1
      fi
      if ! mv -- "${staged_frontend}/node_modules" "${live_frontend}/node_modules"; then
        if ((had_node_modules)); then
          mv -- "${previous_frontend}/node_modules" "${live_frontend}/node_modules"
        fi
        if ((had_dist)); then
          mv -- "${previous_frontend}/dist" "${live_frontend}/dist"
        fi
        return 1
      fi
      if ! mv -- "${staged_frontend}/dist" "${live_frontend}/dist"; then
        mv -- "${live_frontend}/node_modules" "${staged_frontend}/node_modules"
        if ((had_node_modules)); then
          mv -- "${previous_frontend}/node_modules" "${live_frontend}/node_modules"
        fi
        if ((had_dist)); then
          mv -- "${previous_frontend}/dist" "${live_frontend}/dist"
        fi
        return 1
      fi
    }
    acquire_lock
    workspace_stage "检查升级条件" "请确认部署目录干净、磁盘空间充足，且更新包对应当前产品。" E_UPDATE_CHECK
    project_status=""
    if ! project_status="$(git -C "${PROJECT_DIR}" status --porcelain)"; then
      fail "无法读取部署目录的 Git 状态，请检查目录和权限。"
    fi
    [[ -z "${project_status}" ]] || fail "部署目录存在本地改动；请先妥善保存并处理改动，更新器不会自动丢弃文件。"
    [[ "$(stat -c '%u' "${PROJECT_DIR}")" -eq 0 ]] || fail "部署目录必须由 root 持有，请检查安装权限。"
    if [[ -n "${offline_input}" ]]; then
      workspace_stage "校验离线更新包" "核对上传的 bundle 与同名 .sha256；完全断网还需要预先准备依赖缓存。" E_BUNDLE_VERIFY
      prepare_offline_bundle "${offline_input}"
    fi
    workspace_stage "读取目标版本（当前服务保持运行）" "在线更新请检查远程连接与分支；本地包请检查包完整性和历史基线。" E_FETCH
    workspace_run git -C "${PROJECT_DIR}" fetch --no-tags -- "${remote}" "refs/heads/${branch}" || fail "无法读取目标版本，请查看上方 Git 报错。" E_FETCH
    git -C "${PROJECT_DIR}" merge-base --is-ancestor HEAD FETCH_HEAD || {
      fail "目标版本是旧版本或已与当前版本分叉，无法快进升级；请重新打包包含当前提交的新版本。" E_NOT_FORWARD
    }
    old_commit="$(git -C "${PROJECT_DIR}" rev-parse HEAD)"
    new_commit="$(git -C "${PROJECT_DIR}" rev-parse FETCH_HEAD)"
    [[ -z "${expected_commit}" || "${new_commit}" == "${expected_commit}" ]] || fail "导入提交与校验时的目标不一致，更新已取消。" E_BUNDLE_HEAD
    if [[ "${old_commit}" == "${new_commit}" ]]; then
      printf '无需更新：当前已是目标版本 %s；未停服、未修改数据库。\n' "${new_commit}"
      exit 0
    fi
    printf '版本：%s → %s\n' "${old_commit}" "${new_commit}"
    workspace_stage "检查构建依赖与磁盘空间" "补齐 Python、uv、npm，或清理无关文件/扩容；不要删除回滚快照。" E_DEPENDENCY
    [[ -x "${PYTHON_BIN}" ]] || fail "Python 环境缺失，请先修复部署环境。" E_DEPENDENCY
    command -v uv >/dev/null && command -v npm >/dev/null || fail "更新需要 uv 和 npm；请先修复运行时安装。" E_DEPENDENCY
    workspace_require_space "${PROJECT_DIR}" "$(( $(du -sb "${PROJECT_DIR}/frontend" | cut -f1) + 536870912 ))"
    database_bytes="$(stat -c '%s' -- "$(active_database_path)")"
    workspace_require_space "${BACKUP_DIR}" "$((database_bytes * 2 + 104857600))"
    [[ "$(git -C "${PROJECT_DIR}" cat-file -t "${new_commit}:frontend")" == "tree" ]] || {
      fail "目标提交缺少前端目录，可能不是本产品的升级包。"
    }
    frontend_symlinks="$(
      git -C "${PROJECT_DIR}" ls-tree -r "${new_commit}" frontend \
        | awk '$1 == "120000" { print }'
    )"
    [[ -z "${frontend_symlinks}" ]] || {
      fail "目标前端包含符号链接，更新器拒绝构建；请检查发布内容。"
    }
    install -d -m 0750 -o "${FRONTEND_USER}" -g "${FRONTEND_GROUP}" \
      "${NPM_CACHE_DIR}"
    if [[ ! -d "${NPM_CACHE_DIR}/_cacache" && -d /root/.npm/_cacache ]]; then
      cp -a -- /root/.npm/_cacache "${NPM_CACHE_DIR}/_cacache"
      chown -R "${FRONTEND_USER}:${FRONTEND_GROUP}" "${NPM_CACHE_DIR}/_cacache"
    fi
    frontend_stage_dir="$(mktemp -d "${PROJECT_DIR}.frontend-update.XXXXXXXX")"
    frontend_archive="${frontend_stage_dir}/frontend.tar"
    log "Installing and building the candidate frontend while the current version is online"
    workspace_stage "安装依赖并构建新版前端（当前服务保持运行）" "检查日志中的 npm/构建报错；bundle 不含依赖，缓存不足时需要 npm 软件源。" E_FRONTEND_BUILD
    if ! (
      umask 0022 &&
      git -C "${PROJECT_DIR}" archive --format=tar \
        --output="${frontend_archive}" "${new_commit}" frontend &&
      tar --no-same-owner --no-same-permissions \
        -xf "${frontend_archive}" -C "${frontend_stage_dir}" &&
      rm -f -- "${frontend_archive}" &&
      test -d "${frontend_stage_dir}/frontend" &&
      test ! -L "${frontend_stage_dir}/frontend" &&
      chown -R "${FRONTEND_USER}:${FRONTEND_GROUP}" "${frontend_stage_dir}" &&
      workspace_run run_as_frontend npm --prefix "${frontend_stage_dir}/frontend" \
        ci --include=dev --prefer-offline --no-audit --no-fund &&
      workspace_run run_as_frontend npm --prefix "${frontend_stage_dir}/frontend" run build &&
      validate_staged_frontend &&
      chown -R root:root "${frontend_stage_dir}" &&
      chmod -R u=rwX,go=rX "${frontend_stage_dir}" &&
      chmod 0700 "${frontend_stage_dir}" &&
      validate_staged_frontend
    ); then
      cleanup_frontend_stage || true
      fail "新版前端依赖安装或构建失败；本次更新尚未停止原服务。"
    fi
    [[ "$(stat -c '%d' "${frontend_stage_dir}")" == \
      "$(stat -c '%d' "${PROJECT_DIR}/frontend")" ]] || {
      cleanup_frontend_stage || true
      fail "前端暂存目录与部署目录不在同一文件系统，无法安全切换。"
    }
    if ! update_dir="$(new_operation_dir updates)"; then
      cleanup_frontend_stage || true
      fail "无法创建升级回滚目录；请检查备份分区权限和空间，尚未停止原服务。"
    fi
    workspace_stage "停服并创建升级前备份" "检查备份空间及服务停止错误；此阶段失败会尝试恢复原服务。" E_BACKUP
    if ! stop_for_maintenance; then
      cleanup_frontend_stage || true
      fail "无法确认所有应用和备份服务已停止；未应用更新。"
    fi
    if ! create_backup "${update_dir}"; then
      cleanup_frontend_stage || true
      fail "离线备份失败；未应用更新。"
    fi
    if ! update_backup="$(backup_file_in "${update_dir}")"; then
      cleanup_frontend_stage || true
      fail "找不到升级回滚快照，尚未应用更新。"
    fi
    RECOVERY_SNAPSHOT="${update_backup}"
    install -m 0640 -o root -g "${APP_GROUP}" "${ENV_FILE}" "${update_dir}/app.env.before"
    if ! chown root:"${APP_GROUP}" "${update_dir}" \
      || ! chmod 0750 "${update_dir}"; then
      cleanup_frontend_stage || true
      fail "无法收紧升级回滚目录权限，尚未应用更新。"
    fi
    update_failed() {
      local status="$1"
      WORKSPACE_ERROR="升级过程被中断；保留回滚目录，按下方状态处理。"
      WORKSPACE_CODE=E_INTERRUPTED
      exit "${status}"
    }
    trap 'update_failed 130' INT
    trap 'update_failed 143' TERM
    cat >"${update_dir}/update.env" <<EOF
OLD_COMMIT=${old_commit}
NEW_COMMIT=${new_commit}
DATABASE_BACKUP=${update_backup}
FRONTEND_RUNTIME_BACKUP=${frontend_stage_dir}/previous
FRONTEND_RUNTIME_SWAPPED=false
EOF
    chown root:"${APP_GROUP}" "${update_dir}/update.env"
    chmod 0640 "${update_dir}/update.env"
    set_frontend_runtime_state false
    sync -f "${update_dir}/app.env.before"
    DATA_MAY_HAVE_CHANGED=true
    workspace_stage "应用目标代码和 Python 依赖" "依赖错误请检查 uv 日志和软件源；此阶段失败保持维护状态，勿直接启动。" E_BACKEND_INSTALL
    workspace_run git -C "${PROJECT_DIR}" merge --ff-only "${new_commit}"
    export UV_PYTHON_INSTALL_DIR UV_CACHE_DIR
    (
      cd "${PROJECT_DIR}"
      workspace_run uv sync --frozen --no-dev --python 3.12
    )
    set_frontend_runtime_state in_progress
    swap_frontend_runtime
    set_frontend_runtime_state true
    chown -R root:root "${PROJECT_DIR}"
    # Git creates replaced files using the updater's restrictive umask. Restore
    # read/search access for the unprivileged runtime accounts before startup.
    chmod -R u=rwX,go=rX "${PROJECT_DIR}"
    unreadable_backend_file="$(
      "${RUNUSER_BIN}" -u "${APP_USER}" -- \
        find "${PROJECT_DIR}/app" -type f ! -readable -print -quit
    )"
    [[ -z "${unreadable_backend_file}" ]] || {
      fail "后端账号无法读取 ${unreadable_backend_file}，请检查发布文件权限。"
    }
    "${RUNUSER_BIN}" -u "${APP_USER}" -- test -r "${PROJECT_DIR}/server.py"
    "${RUNUSER_BIN}" -u "${FRONTEND_USER}" -- \
      test -r "${PROJECT_DIR}/frontend/node_modules/vinext/dist/cli.js"
    "${RUNUSER_BIN}" -u "${FRONTEND_USER}" -- \
      test -r "${PROJECT_DIR}/frontend/dist/server/index.js"
    workspace_stage "执行数据库迁移" "查看迁移报错；保留回滚快照，按版本感知回滚步骤处理。" E_MIGRATION
    workspace_run run_app_env "${ALEMBIC_BIN}" upgrade head
    workspace_stage "安装服务并验证运行状态" "检查后端、前端及备份定时器；使用 status、logs 定位失败服务。" E_HEALTH
    workspace_run bash "${PROJECT_DIR}/deploy/systemd/install.sh" \
      "${PROJECT_DIR}" "${APP_USER}" "${FRONTEND_USER}" "${NODE_BIN}" \
      "${ENV_FILE}" "${DATA_DIR}" "${BACKUP_DIR}" \
      "${FRONTEND_PORT}" "${BACKEND_PORT}"
    health_check 12 2
    run_app_env "${ALEMBIC_BIN}" current
    systemctl is-active --quiet solution-workspace-backup.timer
    systemctl is-enabled --quiet solution-workspace-backup.timer
    MAINTENANCE_STARTED=false
    trap - ERR INT TERM
    if ! cleanup_frontend_stage; then
      printf 'warning: could not remove frontend staging directory after success\n' >&2
    fi
    printf 'update completed: %s -> %s\n' "${old_commit}" "${new_commit}"
    printf 'offline rollback snapshot: %s\n' "${update_backup}"
    ;;
  *)
    fail "unknown command: ${COMMAND}; run 'solution-workspace help'"
    ;;
esac
