#!/usr/bin/env bash
set -Eeuo pipefail
umask 0077

readonly DEFAULT_CONFIG_FILE="/etc/solution-workspace/deploy.conf"
CONFIG_FILE="${SOLUTION_WORKSPACE_CONFIG:-${DEFAULT_CONFIG_FILE}}"

usage() {
  cat <<'EOF'
Solution Workspace operations command.

Usage:
  sudo solution-workspace COMMAND [arguments]

Commands:
  status                         Show services, timer and health
  health                         Check backend readiness and frontend response
  start | stop | restart         Control the application target
  logs [backend|frontend|backup] [LINES]
                                 Show recent logs (default: both app services, 200)
  backup [OUTPUT_DIR]            Create and verify an online SQLite backup
  verify-db DB_PATH              Verify SQLite integrity and backup manifest
  db-info                        Show active SQLite path and Alembic revision
  switch-db ABSOLUTE_DB_PATH     Switch to an existing or new SQLite database
  promote-db ABSOLUTE_DB_PATH    Clone the frozen active DB and promote the clone
  migrate                        Offline backup, then apply pending migrations
  create-admin LOGIN DISPLAY     Create a super administrator interactively
  update [REMOTE] [BRANCH]       Offline backup, fast-forward, build and deploy
                                 (defaults: origin mvp)
  help                           Show this help

Mutating commands use the root-owned deployment lock, so a backup,
database switch, migration or update cannot run concurrently.
EOF
}

fail() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

log() {
  printf '\n==> %s\n' "$*"
}

COMMAND="${1:-help}"
if [[ "${COMMAND}" == "help" || "${COMMAND}" == "-h" || "${COMMAND}" == "--help" ]]; then
  usage
  exit 0
fi
shift || true

[[ "${EUID}" -eq 0 ]] || fail "run this command with sudo"
[[ -r "${CONFIG_FILE}" ]] || fail "deployment config not found: ${CONFIG_FILE}"
# The file is generated by the root-owned installer and is not user writable.
# shellcheck disable=SC1090
source "${CONFIG_FILE}"

required_values=(
  PROJECT_DIR APP_USER FRONTEND_USER APP_HOME NODE_BIN ENV_FILE DATA_DIR BACKUP_DIR
  FRONTEND_PORT BACKEND_PORT UV_PYTHON_INSTALL_DIR UV_CACHE_DIR LOCK_FILE
)
for required_name in "${required_values[@]}"; do
  [[ -n "${!required_name:-}" ]] || fail "missing ${required_name} in ${CONFIG_FILE}"
done

readonly PYTHON_BIN="${PROJECT_DIR}/.venv/bin/python"
readonly ALEMBIC_BIN="${PROJECT_DIR}/.venv/bin/alembic"
readonly NODE_BIN_DIR="$(dirname -- "${NODE_BIN}")"
readonly APP_GROUP="$(id -gn "${APP_USER}")"
readonly FRONTEND_GROUP="$(id -gn "${FRONTEND_USER}")"
readonly FRONTEND_HOME="/var/lib/solution-workspace-web-home"
readonly NPM_CACHE_DIR="/var/cache/solution-workspace/npm"
export PATH="${NODE_BIN_DIR}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
readonly RUNUSER_BIN="$(command -v runuser || true)"
[[ -x "${RUNUSER_BIN}" ]] || fail "runuser is required; install the util-linux package"

run_as_app() {
  "${RUNUSER_BIN}" -u "${APP_USER}" -- env \
    HOME="${APP_HOME}" \
    PATH="${PATH}" \
    bash -c 'umask 0077; exec "$@"' bash "$@"
}

run_as_frontend() {
  "${RUNUSER_BIN}" -u "${FRONTEND_USER}" -- env -i \
    HOME="${FRONTEND_HOME}" \
    LANG=C.UTF-8 \
    PATH="${PATH}" \
    npm_config_cache="${NPM_CACHE_DIR}" \
    npm_config_update_notifier=false \
    "$@"
}

run_app_env() {
  "${RUNUSER_BIN}" -u "${APP_USER}" -- env \
    HOME="${APP_HOME}" \
    PATH="${PATH}" \
    bash -c '
      set -Eeuo pipefail
      umask 0077
      set -a
      # shellcheck disable=SC1090
      source "$1"
      set +a
      cd "$2"
      shift 2
      exec "$@"
    ' bash "${ENV_FILE}" "${PROJECT_DIR}" "$@"
}

acquire_lock() {
  exec 9>>"${LOCK_FILE}"
  flock --wait 300 9 || fail "another deployment or backup operation is still running"
}

health_check() {
  local attempts="${1:-1}"
  local delay_seconds="${2:-0}"
  local attempt
  for ((attempt = 1; attempt <= attempts; attempt += 1)); do
    if curl --fail --silent --show-error --connect-timeout 3 --max-time 10 \
      "http://127.0.0.1:${BACKEND_PORT}/api/v1/health/ready" >/dev/null \
      && curl --fail --silent --show-error --connect-timeout 3 --max-time 10 \
        "http://127.0.0.1:${FRONTEND_PORT}/" >/dev/null; then
      printf 'health: ok (backend :%s, frontend :%s)\n' \
        "${BACKEND_PORT}" "${FRONTEND_PORT}"
      return 0
    fi
    if ((attempt < attempts)); then
      sleep "${delay_seconds}"
    fi
  done
  printf 'health: failed\n' >&2
  return 1
}

resolve_backup_dir() {
  local requested="$1"
  local backup_root resolved
  backup_root="$(realpath -- "${BACKUP_DIR}")"
  resolved="$(realpath --canonicalize-missing -- "${requested}")"
  [[ "${resolved}" == "${backup_root}" || "${resolved}" == "${backup_root}/"* ]] || {
    fail "backup output must stay inside ${backup_root}"
  }
  [[ ! -L "${requested}" ]] || fail "backup output must not be a symbolic link"
  printf '%s\n' "${resolved}"
}

create_backup() {
  local output_dir
  output_dir="$(resolve_backup_dir "${1:-${BACKUP_DIR}}")"
  install -d -m 0750 -o "${APP_USER}" -g "${APP_GROUP}" "${output_dir}"
  run_app_env "${PYTHON_BIN}" -m app.backup --output-dir "${output_dir}"
}

verify_database() {
  local database_path="$1"
  [[ -f "${database_path}" ]] || fail "database file not found: ${database_path}"
  run_as_app "${PYTHON_BIN}" -c '
import hashlib
import json
import sqlite3
import sys
from pathlib import Path

path = Path(sys.argv[1]).resolve()
with sqlite3.connect(f"file:{path}?mode=ro", uri=True) as db:
    result = db.execute("PRAGMA integrity_check").fetchone()
    tables = {
        row[0]
        for row in db.execute("SELECT name FROM sqlite_master WHERE type = '\''table'\''")
    }
    revision_row = (
        db.execute("SELECT version_num FROM alembic_version LIMIT 1").fetchone()
        if "alembic_version" in tables
        else None
    )
if not result or result[0] != "ok":
    raise SystemExit(f"integrity_check failed: {result}")

manifest_path = path.with_name(path.name + ".manifest.json")
manifest_state = "not present (integrity only)"
if manifest_path.is_file():
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    hasher = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            hasher.update(chunk)
    if manifest.get("databaseFile") != path.name:
        raise SystemExit("manifest databaseFile does not match")
    if manifest.get("sha256") != hasher.hexdigest():
        raise SystemExit("manifest SHA-256 does not match")
    if manifest.get("sizeBytes") != path.stat().st_size:
        raise SystemExit("manifest size does not match")
    manifest_state = "verified"
revision = revision_row[0] if revision_row else "none (empty or pre-migration DB)"
print(
    f"database integrity: ok; manifest: {manifest_state}; "
    f"schema revision: {revision}; file: {path}"
)
' "${database_path}"
}

rewrite_database_url() {
  local new_url="$1"
  local temporary_env
  temporary_env="$(mktemp "${ENV_FILE%/*}/app.env.XXXXXX")"
  awk -v replacement="MVP_DATABASE_URL=${new_url}" '
    BEGIN { replaced = 0 }
    /^MVP_DATABASE_URL=/ {
      print replacement
      replaced = 1
      next
    }
    { print }
    END {
      if (!replaced) {
        print replacement
      }
    }
  ' "${ENV_FILE}" >"${temporary_env}"
  install -m 0640 -o root -g "${APP_GROUP}" "${temporary_env}" "${ENV_FILE}"
  rm -f -- "${temporary_env}"
}

active_database_url() {
  sed -n 's/^MVP_DATABASE_URL=//p' "${ENV_FILE}" | tail -n1
}

active_database_path() {
  local url
  url="$(active_database_url)"
  [[ "${url}" == sqlite:////* ]] || fail "active database is not an absolute SQLite URL"
  realpath --canonicalize-missing -- "${url#sqlite:///}"
}

new_operation_dir() {
  local category="$1"
  local timestamp output_dir
  timestamp="$(date -u +%Y%m%dT%H%M%S%NZ)"
  output_dir="${BACKUP_DIR}/${category}/${timestamp}"
  install -d -m 0750 -o "${APP_USER}" -g "${APP_GROUP}" "${output_dir}" || return 1
  printf '%s\n' "${output_dir}"
}

backup_file_in() {
  local backup_dir="$1"
  local matches
  shopt -s nullglob
  matches=("${backup_dir}"/mvp-*.db)
  shopt -u nullglob
  [[ "${#matches[@]}" -eq 1 ]] || fail "expected one rollback database in ${backup_dir}"
  printf '%s\n' "${matches[0]}"
}

stop_for_maintenance() {
  systemctl stop solution-workspace-backup.timer || return 1
  systemctl stop solution-workspace-backup.service || true
  systemctl stop solution-workspace.target || return 1
}

start_after_maintenance() {
  systemctl start solution-workspace.target || return 1
  systemctl start solution-workspace-backup.timer || return 1
}

clone_sqlite_database() {
  local source_path="$1"
  local target_path="$2"
  run_as_app "${PYTHON_BIN}" -c '
import sqlite3
import sys
from contextlib import closing

source_path, target_path = sys.argv[1:3]
with (
    closing(sqlite3.connect(f"file:{source_path}?mode=ro", uri=True)) as source,
    closing(sqlite3.connect(target_path)) as target,
):
    source.backup(target)
    target.commit()
' "${source_path}" "${target_path}"
  chmod 0600 "${target_path}"
  chown "${APP_USER}:${APP_GROUP}" "${target_path}"
}

checkpoint_database() {
  local database_path="$1"
  run_as_app "${PYTHON_BIN}" -c '
import sqlite3
import sys

with sqlite3.connect(sys.argv[1]) as db:
    db.execute("PRAGMA wal_checkpoint(TRUNCATE)")
    result = db.execute("PRAGMA integrity_check").fetchone()
    if not result or result[0] != "ok":
        raise SystemExit(f"integrity_check failed: {result}")
' "${database_path}"
}

move_database_bundle() {
  local source_path="$1"
  local target_path="$2"
  local suffix
  [[ -f "${source_path}" ]] && mv -- "${source_path}" "${target_path}"
  for suffix in -wal -shm; do
    if [[ -e "${source_path}${suffix}" ]]; then
      mv -- "${source_path}${suffix}" "${target_path}${suffix}"
    fi
  done
}

SWITCH_ACTIVE="false"
SWITCH_ENV_SNAPSHOT=""
SWITCH_TARGET=""
SWITCH_PRESERVED_TARGET=""
SWITCH_CANDIDATE=""
SWITCH_TIMESTAMP=""
SWITCH_SWAPPED="false"

rollback_switch() {
  local reason="$1"
  trap - ERR INT TERM
  set +e
  systemctl stop solution-workspace.target
  systemctl stop solution-workspace-backend.service solution-workspace-frontend.service
  if [[ "${SWITCH_SWAPPED}" == "true" && -f "${SWITCH_TARGET}" ]]; then
    move_database_bundle \
      "${SWITCH_TARGET}" \
      "${SWITCH_TARGET}.failed-${SWITCH_TIMESTAMP}"
  fi
  if [[ -n "${SWITCH_PRESERVED_TARGET}" && -f "${SWITCH_PRESERVED_TARGET}" ]]; then
    move_database_bundle "${SWITCH_PRESERVED_TARGET}" "${SWITCH_TARGET}"
  fi
  if [[ -n "${SWITCH_CANDIDATE}" && -f "${SWITCH_CANDIDATE}" ]]; then
    move_database_bundle "${SWITCH_CANDIDATE}" "${SWITCH_CANDIDATE}.failed"
  fi
  if [[ -f "${SWITCH_ENV_SNAPSHOT}" ]]; then
    install -m 0640 -o root -g "${APP_GROUP}" "${SWITCH_ENV_SNAPSHOT}" "${ENV_FILE}"
  fi
  systemctl start solution-workspace.target
  systemctl start solution-workspace-backup.timer
  health_check 12 2 || true
  SWITCH_ACTIVE="false"
  set -e
  printf 'database switch rolled back: %s\n' "${reason}" >&2
}

switch_error_trap() {
  local status="$1"
  if [[ "${SWITCH_ACTIVE}" == "true" ]]; then
    rollback_switch "unexpected command failure or interruption"
  fi
  exit "${status}"
}

switch_database() {
  local mode="$1"
  local requested_path="$2"
  local target_path data_root current_path rollback_dir rollback_db source_path new_url

  [[ "${requested_path}" == /* ]] || fail "database path must be absolute"
  [[ "${requested_path}" != *[[:space:]]* ]] || fail "database path must not contain whitespace"
  [[ "${requested_path}" != *"'"* ]] || fail "database path must not contain a single quote"
  target_path="$(realpath --canonicalize-missing -- "${requested_path}")"
  data_root="$(realpath -- "${DATA_DIR}")"
  [[ "${target_path}" == "${data_root}/"* ]] || {
    fail "database must stay inside ${data_root} for the systemd sandbox"
  }
  [[ "${target_path}" == *.db ]] || fail "database filename must end in .db"
  acquire_lock
  install -d -m 0750 -o "${APP_USER}" -g "${APP_GROUP}" "$(dirname -- "${target_path}")"
  current_path="$(active_database_path)"
  [[ "${target_path}" != "${current_path}" ]] || fail "target database is already active"

  if [[ "${mode}" == "switch" && -f "${target_path}" ]]; then
    chown "${APP_USER}:${APP_GROUP}" "${target_path}"
    chmod 0600 "${target_path}"
    verify_database "${target_path}"
  elif [[ "${mode}" == "promote" && -e "${target_path}" ]]; then
    fail "promote-db target already exists; choose a new filename"
  fi

  stop_for_maintenance
  if ! rollback_dir="$(new_operation_dir switches)"; then
    start_after_maintenance || true
    fail "cannot create switch rollback directory; unchanged services were restarted"
  fi
  if ! create_backup "${rollback_dir}"; then
    start_after_maintenance || true
    fail "offline backup failed; database switch was not attempted"
  fi
  if ! rollback_db="$(backup_file_in "${rollback_dir}")"; then
    start_after_maintenance || true
    fail "cannot locate switch rollback snapshot; database switch was not attempted"
  fi
  SWITCH_ENV_SNAPSHOT="${rollback_dir}/app.env.before"
  if ! install -m 0640 -o root -g "${APP_GROUP}" \
    "${ENV_FILE}" "${SWITCH_ENV_SNAPSHOT}"; then
    start_after_maintenance || true
    fail "cannot preserve runtime configuration; database switch was not attempted"
  fi
  SWITCH_TIMESTAMP="$(date -u +%Y%m%dT%H%M%S%NZ)"
  SWITCH_TARGET="${target_path}"
  SWITCH_CANDIDATE="${DATA_DIR}/.switch-candidate-${SWITCH_TIMESTAMP}.db"
  SWITCH_PRESERVED_TARGET=""
  SWITCH_SWAPPED="false"
  SWITCH_ACTIVE="true"
  trap 'switch_error_trap $?' ERR
  trap 'switch_error_trap 130' INT
  trap 'switch_error_trap 143' TERM

  if [[ "${mode}" == "promote" ]]; then
    source_path="${rollback_db}"
  elif [[ -f "${target_path}" ]]; then
    checkpoint_database "${target_path}"
    source_path="${target_path}"
  else
    source_path=""
  fi
  if [[ -n "${source_path}" ]]; then
    clone_sqlite_database "${source_path}" "${SWITCH_CANDIDATE}"
  fi

  new_url="sqlite:///${SWITCH_CANDIDATE}"
  rewrite_database_url "${new_url}"
  if ! run_app_env "${ALEMBIC_BIN}" upgrade head; then
    rollback_switch "candidate migration failed"
    fail "database migration failed; original database and configuration were restored"
  fi
  checkpoint_database "${SWITCH_CANDIDATE}"

  if [[ -f "${target_path}" ]]; then
    SWITCH_PRESERVED_TARGET="${target_path}.pre-switch-${SWITCH_TIMESTAMP}"
    move_database_bundle "${target_path}" "${SWITCH_PRESERVED_TARGET}"
  fi
  move_database_bundle "${SWITCH_CANDIDATE}" "${target_path}"
  SWITCH_SWAPPED="true"
  chmod 0600 "${target_path}"
  chown "${APP_USER}:${APP_GROUP}" "${target_path}"
  rewrite_database_url "sqlite:///${target_path}"

  if ! systemctl start solution-workspace.target || ! health_check 12 2; then
    rollback_switch "new database failed service startup or health checks"
    fail "database switch failed; original database and configuration were restored"
  fi
  systemctl start solution-workspace-backup.timer
  SWITCH_ACTIVE="false"
  trap - ERR INT TERM
  printf 'database switch completed: %s\n' "${target_path}"
  printf 'offline rollback snapshot: %s\n' "${rollback_db}"
  if [[ -n "${SWITCH_PRESERVED_TARGET}" ]]; then
    printf 'pre-migration target preserved: %s\n' "${SWITCH_PRESERVED_TARGET}"
  fi
}

case "${COMMAND}" in
  status)
    systemctl --no-pager --full status \
      solution-workspace.target \
      solution-workspace-backend.service \
      solution-workspace-frontend.service \
      solution-workspace-backup.timer || true
    printf '\n'
    health_check || true
    ;;
  health)
    health_check 12 2
    ;;
  start|stop|restart)
    acquire_lock
    systemctl "${COMMAND}" solution-workspace.target
    if [[ "${COMMAND}" != "stop" ]]; then
      health_check 12 2
    fi
    ;;
  logs)
    component="${1:-all}"
    lines="${2:-200}"
    [[ "${lines}" =~ ^[0-9]+$ ]] || fail "LINES must be a non-negative integer"
    case "${component}" in
      backend) units=(-u solution-workspace-backend.service) ;;
      frontend) units=(-u solution-workspace-frontend.service) ;;
      backup) units=(-u solution-workspace-backup.service) ;;
      all) units=(-u solution-workspace-backend.service -u solution-workspace-frontend.service) ;;
      *) fail "logs component must be backend, frontend or backup" ;;
    esac
    journalctl --no-pager --full "${units[@]}" -n "${lines}"
    ;;
  backup)
    acquire_lock
    create_backup "${1:-${BACKUP_DIR}}"
    ;;
  verify-db)
    [[ "$#" -eq 1 ]] || fail "usage: solution-workspace verify-db DB_PATH"
    verify_database "$1"
    ;;
  db-info)
    printf 'database URL: %s\n' "$(active_database_url)"
    run_app_env "${ALEMBIC_BIN}" current
    ;;
  switch-db)
    [[ "$#" -eq 1 ]] || fail "usage: solution-workspace switch-db ABSOLUTE_DB_PATH"
    switch_database switch "$1"
    ;;
  promote-db)
    [[ "$#" -eq 1 ]] || fail "usage: solution-workspace promote-db ABSOLUTE_DB_PATH"
    switch_database promote "$1"
    ;;
  migrate)
    acquire_lock
    stop_for_maintenance
    if ! migration_dir="$(new_operation_dir migrations)"; then
      start_after_maintenance || true
      fail "cannot create migration rollback directory; unchanged services were restarted"
    fi
    if ! create_backup "${migration_dir}"; then
      start_after_maintenance || true
      fail "offline backup failed; unchanged services were restarted"
    fi
    if ! migration_backup="$(backup_file_in "${migration_dir}")"; then
      start_after_maintenance || true
      fail "cannot locate migration rollback snapshot; unchanged services were restarted"
    fi
    if ! run_app_env "${ALEMBIC_BIN}" upgrade head; then
      printf 'migration failed; services remain stopped\n' >&2
      printf 'offline rollback snapshot: %s\n' "${migration_backup}" >&2
      fail "inspect the failure before restoring or restarting"
    fi
    if ! systemctl start solution-workspace.target || ! health_check 12 2; then
      systemctl stop solution-workspace.target || true
      systemctl stop solution-workspace-backend.service solution-workspace-frontend.service || true
      systemctl stop solution-workspace-backup.timer solution-workspace-backup.service || true
      printf 'migration startup/health failed; services remain stopped\n' >&2
      printf 'offline rollback snapshot: %s\n' "${migration_backup}" >&2
      fail "inspect the failure before restoring or restarting"
    fi
    systemctl start solution-workspace-backup.timer
    ;;
  create-admin)
    [[ "$#" -eq 2 ]] || fail 'usage: solution-workspace create-admin LOGIN "DISPLAY NAME"'
    acquire_lock
    run_app_env "${PYTHON_BIN}" -m app.cli create-user "$1" "$2" --role super_admin
    ;;
  update)
    remote="${1:-origin}"
    branch="${2:-mvp}"
    frontend_stage_dir=""
    frontend_runtime_swapped="false"
    cleanup_frontend_stage() {
      local candidate="${frontend_stage_dir:-}"
      local canonical_parent canonical_candidate expected_prefix
      [[ -n "${candidate}" ]] || return 0
      [[ -d "${candidate}" && ! -L "${candidate}" ]] || return 1
      canonical_parent="$(realpath -- "$(dirname -- "${PROJECT_DIR}")")" || return 1
      canonical_candidate="$(realpath -- "${candidate}")" || return 1
      expected_prefix="${canonical_parent}/$(basename -- "${PROJECT_DIR}").frontend-update."
      [[ "${canonical_candidate}" == "${expected_prefix}"* ]] || {
        printf 'refusing to remove unexpected frontend staging path: %s\n' \
          "${canonical_candidate}" >&2
        return 1
      }
      rm -rf -- "${canonical_candidate}" || return 1
      frontend_stage_dir=""
    }
    validate_staged_frontend() {
      local staged_frontend="${frontend_stage_dir}/frontend"
      local candidate_path expected_path
      [[ -d "${staged_frontend}" && ! -L "${staged_frontend}" ]] || return 1
      expected_path="$(realpath -- "${frontend_stage_dir}")/frontend"
      [[ "$(realpath -- "${staged_frontend}")" == "${expected_path}" ]] || return 1
      for candidate_path in node_modules dist; do
        [[ -d "${staged_frontend}/${candidate_path}" ]] || return 1
        [[ ! -L "${staged_frontend}/${candidate_path}" ]] || return 1
        [[ "$(realpath -- "${staged_frontend}/${candidate_path}")" == \
          "${expected_path}/${candidate_path}" ]] || return 1
      done
      [[ -f "${staged_frontend}/node_modules/vinext/dist/cli.js" ]] || return 1
      [[ ! -L "${staged_frontend}/node_modules/vinext/dist/cli.js" ]] || return 1
      [[ "$(realpath -- "${staged_frontend}/node_modules/vinext/dist/cli.js")" == \
        "${expected_path}/node_modules/vinext/dist/cli.js" ]] || return 1
      [[ -f "${staged_frontend}/dist/server/index.js" ]] || return 1
      [[ ! -L "${staged_frontend}/dist/server/index.js" ]] || return 1
      [[ "$(realpath -- "${staged_frontend}/dist/server/index.js")" == \
        "${expected_path}/dist/server/index.js" ]] || return 1
    }
    set_frontend_runtime_state() {
      local state="$1"
      case "${state}" in
        false|in_progress|true) ;;
        *) return 1 ;;
      esac
      sed -i "s/^FRONTEND_RUNTIME_SWAPPED=.*$/FRONTEND_RUNTIME_SWAPPED=${state}/" \
        "${update_dir}/update.env" || return 1
      sync -f "${update_dir}/update.env" || return 1
      sync -f "${update_dir}" || return 1
      frontend_runtime_swapped="${state}"
    }
    swap_frontend_runtime() {
      local staged_frontend="${frontend_stage_dir}/frontend"
      local live_frontend="${PROJECT_DIR}/frontend"
      local previous_frontend="${frontend_stage_dir}/previous"
      local had_node_modules=0
      local had_dist=0

      validate_staged_frontend || return 1
      install -d -m 0700 "${previous_frontend}"
      if [[ -e "${live_frontend}/node_modules" ]]; then
        mv -- "${live_frontend}/node_modules" "${previous_frontend}/node_modules"
        had_node_modules=1
      fi
      if [[ -e "${live_frontend}/dist" ]]; then
        if ! mv -- "${live_frontend}/dist" "${previous_frontend}/dist"; then
          if ((had_node_modules)); then
            mv -- "${previous_frontend}/node_modules" "${live_frontend}/node_modules"
          fi
          return 1
        fi
        had_dist=1
      fi
      if ! mv -- "${staged_frontend}/node_modules" "${live_frontend}/node_modules"; then
        if ((had_node_modules)); then
          mv -- "${previous_frontend}/node_modules" "${live_frontend}/node_modules"
        fi
        if ((had_dist)); then
          mv -- "${previous_frontend}/dist" "${live_frontend}/dist"
        fi
        return 1
      fi
      if ! mv -- "${staged_frontend}/dist" "${live_frontend}/dist"; then
        mv -- "${live_frontend}/node_modules" "${staged_frontend}/node_modules"
        if ((had_node_modules)); then
          mv -- "${previous_frontend}/node_modules" "${live_frontend}/node_modules"
        fi
        if ((had_dist)); then
          mv -- "${previous_frontend}/dist" "${live_frontend}/dist"
        fi
        return 1
      fi
    }
    project_status=""
    if ! project_status="$(git -C "${PROJECT_DIR}" status --porcelain)"; then
      fail "cannot inspect the managed release checkout"
    fi
    [[ -z "${project_status}" ]] || fail "managed release checkout has local changes"
    [[ "$(stat -c '%u' "${PROJECT_DIR}")" -eq 0 ]] || fail "managed release must be root-owned"
    acquire_lock
    log "Fetching ${remote}/${branch} while the current version is still online"
    git -C "${PROJECT_DIR}" fetch --prune "${remote}" "${branch}"
    git -C "${PROJECT_DIR}" merge-base --is-ancestor HEAD FETCH_HEAD || {
      fail "remote update is not a fast-forward"
    }
    old_commit="$(git -C "${PROJECT_DIR}" rev-parse HEAD)"
    new_commit="$(git -C "${PROJECT_DIR}" rev-parse FETCH_HEAD)"
    [[ "$(git -C "${PROJECT_DIR}" cat-file -t "${new_commit}:frontend")" == "tree" ]] || {
      fail "candidate commit does not contain a frontend tree"
    }
    frontend_symlinks="$(
      git -C "${PROJECT_DIR}" ls-tree -r "${new_commit}" frontend \
        | awk '$1 == "120000" { print }'
    )"
    [[ -z "${frontend_symlinks}" ]] || {
      fail "candidate frontend must not contain tracked symbolic links"
    }
    install -d -m 0750 -o "${FRONTEND_USER}" -g "${FRONTEND_GROUP}" \
      "${NPM_CACHE_DIR}"
    if [[ ! -d "${NPM_CACHE_DIR}/_cacache" && -d /root/.npm/_cacache ]]; then
      cp -a -- /root/.npm/_cacache "${NPM_CACHE_DIR}/_cacache"
      chown -R "${FRONTEND_USER}:${FRONTEND_GROUP}" "${NPM_CACHE_DIR}/_cacache"
    fi
    frontend_stage_dir="$(mktemp -d "${PROJECT_DIR}.frontend-update.XXXXXXXX")"
    frontend_archive="${frontend_stage_dir}/frontend.tar"
    log "Installing and building the candidate frontend while the current version is online"
    if ! (
      umask 0022 &&
      git -C "${PROJECT_DIR}" archive --format=tar \
        --output="${frontend_archive}" "${new_commit}" frontend &&
      tar --no-same-owner --no-same-permissions \
        -xf "${frontend_archive}" -C "${frontend_stage_dir}" &&
      rm -f -- "${frontend_archive}" &&
      test -d "${frontend_stage_dir}/frontend" &&
      test ! -L "${frontend_stage_dir}/frontend" &&
      chown -R "${FRONTEND_USER}:${FRONTEND_GROUP}" "${frontend_stage_dir}" &&
      run_as_frontend npm --prefix "${frontend_stage_dir}/frontend" \
        ci --include=dev --prefer-offline --no-audit --no-fund &&
      run_as_frontend npm --prefix "${frontend_stage_dir}/frontend" run build &&
      validate_staged_frontend &&
      chown -R root:root "${frontend_stage_dir}" &&
      chmod -R u=rwX,go=rX "${frontend_stage_dir}" &&
      chmod 0700 "${frontend_stage_dir}" &&
      validate_staged_frontend
    ); then
      cleanup_frontend_stage || true
      fail "candidate frontend install/build failed; the current version is still online"
    fi
    [[ "$(stat -c '%d' "${frontend_stage_dir}")" == \
      "$(stat -c '%d' "${PROJECT_DIR}/frontend")" ]] || {
      cleanup_frontend_stage || true
      fail "frontend staging and release checkout must be on the same filesystem"
    }
    if ! update_dir="$(new_operation_dir updates)"; then
      cleanup_frontend_stage || true
      fail "cannot create update rollback directory; the current version is still online"
    fi
    if ! stop_for_maintenance; then
      cleanup_frontend_stage || true
      start_after_maintenance || true
      fail "cannot enter maintenance mode; current services were restarted"
    fi
    if ! create_backup "${update_dir}"; then
      cleanup_frontend_stage || true
      start_after_maintenance || true
      fail "offline backup failed; update was not applied and services were restarted"
    fi
    if ! update_backup="$(backup_file_in "${update_dir}")"; then
      cleanup_frontend_stage || true
      start_after_maintenance || true
      fail "cannot locate update rollback snapshot; update was not applied"
    fi
    if ! chown root:"${APP_GROUP}" "${update_dir}" \
      || ! chmod 0750 "${update_dir}"; then
      cleanup_frontend_stage || true
      start_after_maintenance || true
      fail "cannot seal update rollback directory; update was not applied"
    fi
    update_failed() {
      local status="$1"
      trap - ERR INT TERM
      systemctl stop solution-workspace.target || true
      systemctl stop solution-workspace-backend.service solution-workspace-frontend.service || true
      systemctl stop solution-workspace-backup.timer || true
      systemctl stop solution-workspace-backup.service || true
      printf '\nUPDATE FAILED. Application and backup timer remain stopped.\n' >&2
      printf 'Old commit: %s\nNew commit: %s\nRollback snapshot: %s\n' \
        "${old_commit}" "${new_commit}" "${update_backup}" >&2
      printf 'Frontend staging/rollback directory: %s\n' \
        "${frontend_stage_dir}" >&2
      printf 'Frontend runtime swapped: %s\n' \
        "${frontend_runtime_swapped}" >&2
      if [[ -f "${update_dir}/update.env" ]]; then
        set_frontend_runtime_state "${frontend_runtime_swapped}" || true
      fi
      printf 'Follow the version-aware rollback procedure in docs/UBUNTU_DEPLOYMENT.md.\n' >&2
      exit "${status}"
    }
    trap 'update_failed $?' ERR
    trap 'update_failed 130' INT
    trap 'update_failed 143' TERM
    cat >"${update_dir}/update.env" <<EOF
OLD_COMMIT=${old_commit}
NEW_COMMIT=${new_commit}
DATABASE_BACKUP=${update_backup}
FRONTEND_RUNTIME_BACKUP=${frontend_stage_dir}/previous
FRONTEND_RUNTIME_SWAPPED=false
EOF
    chown root:"${APP_GROUP}" "${update_dir}/update.env"
    chmod 0640 "${update_dir}/update.env"
    git -C "${PROJECT_DIR}" merge --ff-only FETCH_HEAD
    export UV_PYTHON_INSTALL_DIR UV_CACHE_DIR
    (
      cd "${PROJECT_DIR}"
      uv sync --frozen --no-dev --python 3.12
    )
    set_frontend_runtime_state in_progress
    swap_frontend_runtime
    set_frontend_runtime_state true
    chown -R root:root "${PROJECT_DIR}"
    # Git creates replaced files using the updater's restrictive umask. Restore
    # read/search access for the unprivileged runtime accounts before startup.
    chmod -R u=rwX,go=rX "${PROJECT_DIR}"
    unreadable_backend_file="$(
      "${RUNUSER_BIN}" -u "${APP_USER}" -- \
        find "${PROJECT_DIR}/app" -type f ! -readable -print -quit
    )"
    [[ -z "${unreadable_backend_file}" ]] || {
      fail "backend service account cannot read ${unreadable_backend_file}"
    }
    "${RUNUSER_BIN}" -u "${APP_USER}" -- test -r "${PROJECT_DIR}/server.py"
    "${RUNUSER_BIN}" -u "${FRONTEND_USER}" -- \
      test -r "${PROJECT_DIR}/frontend/node_modules/vinext/dist/cli.js"
    "${RUNUSER_BIN}" -u "${FRONTEND_USER}" -- \
      test -r "${PROJECT_DIR}/frontend/dist/server/index.js"
    run_app_env "${ALEMBIC_BIN}" upgrade head
    bash "${PROJECT_DIR}/deploy/systemd/install.sh" \
      "${PROJECT_DIR}" "${APP_USER}" "${FRONTEND_USER}" "${NODE_BIN}" \
      "${ENV_FILE}" "${DATA_DIR}" "${BACKUP_DIR}" \
      "${FRONTEND_PORT}" "${BACKEND_PORT}"
    health_check 12 2
    trap - ERR INT TERM
    if ! cleanup_frontend_stage; then
      printf 'warning: could not remove frontend staging directory after success\n' >&2
    fi
    printf 'update completed: %s -> %s\n' "${old_commit}" "${new_commit}"
    printf 'offline rollback snapshot: %s\n' "${update_backup}"
    ;;
  *)
    fail "unknown command: ${COMMAND}; run 'solution-workspace help'"
    ;;
esac
